(function (window, document) {

    let translation_map = new Map();

    window.addEventListener("load", onLoad);

    function onLoad(event){
        // Generate dom text with json generated by python script.
        setupIDs();
        fetch('./translation_data/config.json')
            .then((response) => response.json())
            .then((json) => {
                let raw_categories=json[0];
                applyHeaders(raw_categories)
                applyPages(raw_categories.pages);
                fetch('./translation_data/en.json')
                    .then((response) => response.json())
                    .then((language) => {
                        translation_map.forEach((array, index, map) => {
                            if(language[index]){
                                for(let i=0; i<array.length; i++)
                                {
                                    array[i].innerHTML = language[index];
                                }
                            }
                        })
                    });
            });
    }

    function setupIDs(){
        menu_page_template = document.querySelector("#menu_page_template");
        page_template = document.querySelector("#content_page_template");
        paragraph_template = document.querySelector("#content_page_template");
    }

    function applyHeaders(categories)
    {
        applyRawText(document, "header_category_title", categories.title);
        applyRawText(document, "header_category_sub_title", categories.sub_title);
        applyRawText(document, "menu_category_title", categories.title);
    }

    function applyPages(pages){
        // Menu 
        for(let i=0; i< pages.length;i++){
            const page = pages[i]
            let node = menu_page_template.cloneNode(true);
            applyHref(node, "menu_page_template_title", page.title.raw)
            applyRawText(node, "menu_page_template_title", page.title);
            document.querySelector("#menu_page_list").appendChild(node); 
        }
        removeElement(menu_page_template);
        // Page content
        for(let i=0; i< pages.length;i++){
            const page = pages[i]
            console.log(page)
            let node = page_template.cloneNode(true);
            applyRawText(node, "content_page_template_title", page.title);
            applyParentID(node, "content_page_template_title", page.title.raw)
            document.querySelector("#content_list").appendChild(node); 
            applyParagraph(node, page.paragraphs);
            
        }
        removeElement(page_template);

    }

    function applyParagraph(root, paragraphs){
        for(let i=0; i< paragraphs.length;i++){
            const paragraph = paragraphs[i]
            console.log(paragraph.title)
            let node = paragraph_template.cloneNode(true);
            applyRawText(node, "content_paragraph_template_title", paragraph.title);
            applyRawText(node, "content_paragraph_template_text", paragraph.text);
            console.log(root)
            root.appendChild(node); 
            
        }
    }

    function applyParentID(root, refId, parentId){
        root.querySelector("#"+refId).parentNode.id = parentId
    }

    function applyHref(root, id, href){
        root.querySelector("#"+id).href = "#"+href;
    }

    function applyRawText(root, id, text){
        if(text!=null){
            setText(root, id, text.raw, true);
        }else{
            setText(root, id, text, true);
        }
    }

    function setText(root, id, text, applyId){
        if(text != null){
            if(text!=""){
                if(text == "CP_help_page_blank"){
                    root.querySelector("#"+id).innerHTML = "";
                }else{
                    root.querySelector("#"+id).innerHTML = "raw: " + text;
                }
            }else{
                root.querySelector("#"+id).innerHTML = text;
            }
            if(applyId){
                let obj;
                if(translation_map.has(text)){
                    obj = translation_map.get(text);
                }else{
                    obj = [];
                }
                obj[obj.length] = root.querySelector("#"+id);
                translation_map.set(text, obj);
            }
        }else{
            root.querySelector("#"+id).innerHTML = "missing:"+id;
        }
    }

    function removeElement(node){
        node.parentNode.removeChild(node);
    }


/*
        <div id="main">
        <div class="header">
            <h1 id="header_category_title"></h1>
            <h2 id="header_category_sub_title"></h2>
        </div>

        <div class="content" id="content_page_template">
            <h2 class="content-subhead" id="content_page_title_template"></h2>
            <div id="content_paragraph_template">
                <h3 class="content-subhead"><u id="content_paragraph_title_template"></u></h3>
                <p id="content_paragraph_text_template"></p>
            </div>
        </div>
        */
    

}(this, this.document));