
# Workflow to move the content of /data passed in from Courseplay_FS22 to /translation_data.

name: Pre-deploy
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  move-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          if [ -d data ]; then
            rm -r translation_data
            mv data translation_data
          fi
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Moved data for Courseplay_FS22'
